### ISSUE TITLE
Client Crash due to Optifine 

### ISSUE THREAD

**Issue by Gamerbolts** [primetoxinz/StacksOnStacks#11]
Hi, I am not sure if this mod even allows modded ingots to be placed or works with a resource pack, but I downloaded the mod and ran it on my modpack. I placed a silver ingot I think it was down and it froze then crashed my client. This is the error log http://pastebin.com/yNDtDS5R

If it is because your mod doesn't allow for modded blocks that is fine, but if it is something that can be fixed thought i'd send it your way

Thanks for the assistance!

**Comment by primetoxinz** [comment]
what mod was the silver ingot from? this is a very unusual crash that I haven't seen before. mods and resourcepacks should work just fine

**Comment by Gamerbolts** [comment]
I just ran MC again and tried testing just vanilla and it crashed same error. I am using Sphax. I wonder if that could be the issue. I'll try to do it again without sphax on and see what happens

Just tested it with no Sphax and it crashed upon loading the world because the ingot was still there. This one was a vanilla Iron ingot. Same crash. There must be a conflict somewhere :( I have 170 mods so it would take forever to pinpoint which one is the issue.

**Comment by primetoxinz** [comment]
I tried sphax myself and it definitely has no issues, so if you could find out all the mods with ingots in your pack that would be useful

**Comment by Gamerbolts** [comment]
hmm interesting. ok i'll work on that and see if I can find the problem mod

**Comment by primetoxinz** [comment]
are you positive it was caused by placing an ingot? because the code that crashed should never be called by SoS....

**Comment by Gamerbolts** [comment]
Yep i saw the grid on the ground and placed a normal iron ingot. Took out all the mods that added ingots, and now testing again

**Comment by primetoxinz** [comment]
ok, my bad. I completely overlooked the fact that you have optifine. optifine is the cause and I cannot fix it

**Comment by Gamerbolts** [comment]
oh? dang. I need optifine to be able to run this modpack. Ok thanks for checking it out for me.

**Comment by primetoxinz** [comment]
I might see if I can figure a way to fix it or ask around, might take some time

**Comment by Gamerbolts** [comment]
Not a problerm. I'll be looking out for an update if it comes. Thanks so much for the help!

**Comment by primetoxinz** [comment]
sorry to say, but this is known issue with many mods and optifine and frankly cannot be fixed.
