### ISSUE TITLE
Placing Ingots Deletes Half Blocks

### ISSUE THREAD

**Issue by Darkosto** [primetoxinz/StacksOnStacks#13]
Hello!

I've found when placing an ingot over a half-slab/block will delete the block. To replicate this: Place down a half-slab in front of another block. Place the ingots directly over the half-slab by clicking on the block behind the half-slab. The half block should be deleted.

Clip of bug: https://clips.twitch.tv/darkosto/CooperativeCarabeefPipeHype

I'm using version: 2-1.1.3
Minecraft version: 1.10.2
Forge Version: 2038

If you need any more information I can gladly show you. I'm also able to give a demonstration on my stream if necessary.  twitch.tv/Darkosto

Thanks!
Darkosto

**Comment by primetoxinz** [comment]
Thanks for the very descriptive report!
