### ISSUE TITLE
crash when right clicking Refined Storages items with ingot

### ISSUE THREAD

**Issue by armyveteran** [primetoxinz/StacksOnStacks#15]
Currently playing Minecraft 1.10.2 with
StacksOnStacks 1.1.4
Forge 12.18.2.2166

Whenever I click on a RefinedStorage item (exporter, importer, external storage, etc.) the game crashes
This is on a SP world
Refined Storage has been notified and they believe it to be an issue with trying to "stack" the ingot onto the item due to StacksOnStacks' feature
This appears to happen with all ingots, although I have not tested all of them (only about 5 or 6)
This does not appear to happen when right clicking those items with other items in my hands, just items that StacksOnStacks allows to be placed in world

[crash-2016-12-07_21.32.38-client.txt](https://github.com/primetoxinz/StacksOnStacks/files/638364/crash-2016-12-07_21.32.38-client.txt)

[crash-2016-12-06_14.34.32-client.txt](https://github.com/primetoxinz/StacksOnStacks/files/638365/crash-2016-12-06_14.34.32-client.txt)

**Comment by madxmike** [comment]
Pretty sure I know what's going on and how to fix it. I'll look into it later today.

**Comment by madxmike** [comment]
Unfortunately this is just an issue that's going to exist in this current version of the mod. I'm currently rewriting the mod for 1.11 then backporting it to 1.10 and don't have to time to relearn how the current version works and debug it. Sorry for the inconvenience.
