### ISSUE TITLE
Can't break a pile of ingots even in creative mode

### ISSUE THREAD

**Issue by itanshi** [primetoxinz/StacksOnStacks#17]
Chucnk is unclaimed, spots open in inventory featured should get ingots

http://imgur.com/a/y1zeQ

These were shift clicked into position when trying to open a gate.

version 2.1.0.62 featured in sky factory 3

**Comment by primetoxinz** [comment]
Stacks for some reason sometimes cause an error when attempting to break, I could not find a reason for this error when I originally saw it. I can look into it again, but usually if you just keep trying to break it they eventually break.

**Comment by itanshi** [comment]
is there a command we can replace it with air?

**Comment by primetoxinz** [comment]
`/setblock ~ ~-1 ~ air` while standing directly on top of it should work

**Comment by madxmike** [comment]
@primetoxinz I'm pretty sure this is to do with accessing the tile information from the world vs from the block state. If you feel like trying to fix it in this version I'll send you some more info on it.

If not then unfortunately this is just an issue that's going to exist in this current version of the mod. I'm currently rewriting the mod for 1.11 then backporting it to 1.10 and don't have to time to relearn how the current version works and debug it. Sorry for the inconvenience.
