### ISSUE TITLE
1.7.10 source?

### ISSUE THREAD

**Issue by ghost** [primetoxinz/StacksOnStacks#20]

**Comment by madxmike** [comment]
I don't have it anymore, and I really doubt @primetoxinz has it. Sorry.

**Comment by ghost** [comment]
damn, i'll decompile it from a jar and try to fix it (obfuscated tho)

**Comment by primetoxinz** [comment]
You can use bearded octo nemesis to deobfuscate it. Would give a link but on phone tn

**Comment by madxmike** [comment]
https://github.com/immibis/bearded-octo-nemesis there you go

**Comment by ghost** [comment]
Good to know that's a thing, thanks for the link :)

**Comment by madxmike** [comment]
Honestly the obfuscated Minecraft code might be easier to understand than the actual mod code for that version lol :P Good luck and let me know if you have any questions.
