### ISSUE TITLE
CME when breaking piles 

### ISSUE THREAD

**Issue by primetoxinz** [primetoxinz/StacksOnStacks#5]
https://gist.github.com/primetoxinz/b96c88a2574bae4b9c32fc09a20a6582

**Comment by madxmike** [comment]
This looks like the multipart removed itself from the world while the world was still updating it. I don't think either of the try/catches in PartIngot would cause it since we iterate through like you're supposed to.

**Comment by primetoxinz** [comment]
You saying this could be a direct multipart bug?

**Comment by madxmike** [comment]
I wouldn't assume it just yet, but it is weird. The game crashes while the world is iterating over the tiles so I would assume something is modifying the tile during this process

**Comment by primetoxinz** [comment]
it's not crashing while iterating over the tile, it's crashing while iterating over an entity of some sort

**Comment by madxmike** [comment]
Tiles are entities(sorta) welcome to notch code

**Comment by madxmike** [comment]
Scratch that you're right.

**Comment by primetoxinz** [comment]
lol

**Comment by primetoxinz** [comment]
in updateTrackedEntities something is removing or adding to EntityTracker.trackedEntities

**Comment by madxmike** [comment]
trace the remove call when the game crashes back to whatever is calling it

**Comment by primetoxinz** [comment]
more descriptive log https://gist.github.com/primetoxinz/3e3fedd379fbeeac3d6340951d2d937c

**Comment by primetoxinz** [comment]
it's all the items that are being spawn

**Comment by madxmike** [comment]
Its because you're spawning them on a seperate thread causing the game to add them to the world while its updating them. Something like that atleast

**Comment by primetoxinz** [comment]
yep, so take this out of a separate thread?

**Comment by madxmike** [comment]
i don't see why it needs to be in one in the first place so ues

**Comment by primetoxinz** [comment]
I only put it in one because the placement was in one as well and used sleep to cause the delay

**Comment by madxmike** [comment]
There's ways to do it without a pause or seperate threads.

**Comment by madxmike** [comment]
But since you're using an iterator there shouldn't be a possibility of a CME as long as it all stays in the main thread

**Comment by primetoxinz** [comment]
yep, it's fine how it is

**Comment by madxmike** [comment]
I have an idea on how to do the whole delay thing nicely without using a seperate thread. I'll look into it when I get home tomorrow

**Comment by madxmike** [comment]
Also would allow for variable timing on the delay like people seem to want
